# Common vars
availability_zone: melbourne-qh2-uom

# Volume
volumes:
  - vol_name: vol-instance1
    vol_size: 50
  - vol_name: vol-instance2
    vol_size: 100
  - vol_name: vol-instance3
    vol_size: 100
  - vol_name: vol-instance4
    vol_size: 100

# Security group
security_groups:
  - ssh
  - http

# Instance
instances:
  - name: ins-1
    volumes: ['vol-instance1']
    flavor: uom.mse.1c4g
  - name: ins-2
    volumes: ['vol-instance2']
    flavor: uom.mse.2c9g
  - name: ins-3
    volumes: ['vol-instance3']
    flavor: uom.mse.2c9g
  - name: ins-4
    volumes: ['vol-instance4']
    flavor: uom.mse.2c9g

instance_image: NeCTAR Ubuntu 18.04 LTS (Bionic) amd64 (with Docker)
instance_key: group-68-key