---
- name: upload script to ins-2
  become: yes
  copy:
    src: ../script/db-ins-2.sh
    dest: /home/ubuntu/
    mode: 0777
  when: inventory_hostname == "ins-2"

- name: upload script to ins-3
  become: yes
  copy:
    src: ../script/db-ins-3.sh
    dest: /home/ubuntu/
    mode: 0777
  when: inventory_hostname == "ins-3"

- name: upload script to ins-4
  become: yes
  copy:
    src: ../script/db-ins-4.sh
    dest: /home/ubuntu/
    mode: 0777
  when: inventory_hostname == "ins-4"

- name: execute script 1/3
  become: yes
  ansible.builtin.shell: /home/ubuntu/db-ins-4.sh
  register: out
  when: inventory_hostname == "ins-4"

- debug: 
    msg: '{{ out.stdout }}'

- name: execute script 2/3
  become: yes
  ansible.builtin.shell: /home/ubuntu/db-ins-3.sh
  register: out
  when: inventory_hostname == "ins-3"

- debug: 
    msg: '{{ out.stdout }}'

- name: execute script 3/3
  become: yes
  ansible.builtin.shell: /home/ubuntu/db-ins-2.sh
  register: out
  when: inventory_hostname == "ins-2"

- debug: 
    msg: '{{ out.stdout }}'